test_that(".typeCheckVariable INT checks", {
  expect_silent(.typeCheckVariable("x", 1L, "INT", FALSE))
  expect_silent(.typeCheckVariable("x", 1, "INT", FALSE))
  expect_error(.typeCheckVariable("x", 1.5, "INT", FALSE), "scalar of type INT")
  expect_error(.typeCheckVariable("x", NA, "INT", FALSE), "contains NA")
  expect_error(.typeCheckVariable("x", NULL, "INT", FALSE), "not supplied")
  expect_error(.typeCheckVariable("x", c(1L, 2L), "INT", FALSE), "scalar of type INT")
  expect_silent(.typeCheckVariable("x", c(1L, 2L), "INT[]", TRUE))
  expect_error(.typeCheckVariable("x", c(1.5, 2L), "INT[]", TRUE), "array of type INT")
  expect_error(.typeCheckVariable("x", numeric(0), "INT[]", TRUE), "non-empty vector")
})

test_that(".typeCheckVariable BIGINT checks", {
  expect_silent(.typeCheckVariable("x", 123456789012345, "BIGINT", FALSE))
  expect_silent(.typeCheckVariable("x", 1e11, "BIGINT", FALSE))
  expect_silent(.typeCheckVariable("x", 2, "BIGINT", FALSE))
  expect_error(.typeCheckVariable("x", 1.5, "BIGINT", FALSE), "scalar of type BIGINT")
  expect_error(.typeCheckVariable("x", NA, "BIGINT", FALSE), "contains NA")
  expect_error(.typeCheckVariable("x", NULL, "BIGINT", FALSE), "not supplied")
  expect_error(.typeCheckVariable("x", c(1, 2), "BIGINT", FALSE), "scalar of type BIGINT")
  expect_silent(.typeCheckVariable("x", c(1, 2, 3), "BIGINT[]", TRUE))
  expect_error(.typeCheckVariable("x", c(1, 2.5), "BIGINT[]", TRUE), "array of type BIGINT")
  expect_error(.typeCheckVariable("x", numeric(0), "BIGINT[]", TRUE), "non-empty vector")
})

test_that(".typeCheckVariable CHAR checks", {
  expect_silent(.typeCheckVariable("x", "a", "CHAR", FALSE))
  expect_error(.typeCheckVariable("x", 1, "CHAR", FALSE), "scalar of type CHAR")
  expect_error(.typeCheckVariable("x", NA_character_, "CHAR", FALSE), "contains NA")
  expect_error(.typeCheckVariable("x", NULL, "CHAR", FALSE), "not supplied")
  expect_error(.typeCheckVariable("x", c("a", "b"), "CHAR", FALSE), "scalar of type CHAR")
  expect_silent(.typeCheckVariable("x", c("a", "b"), "CHAR[]", TRUE))
  expect_error(.typeCheckVariable("x", c("a", NA_character_), "CHAR[]", TRUE), "contains NA")
  expect_error(.typeCheckVariable("x", character(0), "CHAR[]", TRUE), "non-empty vector")
})

test_that(".typeCheckVariable VARCHAR checks", {
  expect_silent(.typeCheckVariable("x", "hello", "VARCHAR", FALSE))
  expect_error(.typeCheckVariable("x", 1, "VARCHAR", FALSE), "scalar of type VARCHAR")
  expect_error(.typeCheckVariable("x", NA_character_, "VARCHAR", FALSE), "contains NA")
  expect_error(.typeCheckVariable("x", NULL, "VARCHAR", FALSE), "not supplied")
  expect_error(.typeCheckVariable("x", c("a", "b"), "VARCHAR", FALSE), "scalar of type VARCHAR")
  expect_silent(.typeCheckVariable("x", c("a", "b"), "VARCHAR[]", TRUE))
  expect_error(.typeCheckVariable("x", c("a", NA_character_), "VARCHAR[]", TRUE), "contains NA")
  expect_error(.typeCheckVariable("x", character(0), "VARCHAR[]", TRUE), "non-empty vector")
})

test_that(".typeCheckVariable TEXT checks", {
  expect_silent(.typeCheckVariable("x", "some text", "TEXT", FALSE))
  expect_error(.typeCheckVariable("x", 1, "TEXT", FALSE), "scalar of type TEXT")
  expect_error(.typeCheckVariable("x", NA_character_, "TEXT", FALSE), "contains NA")
  expect_error(.typeCheckVariable("x", NULL, "TEXT", FALSE), "not supplied")
  expect_error(.typeCheckVariable("x", c("a", "b"), "TEXT", FALSE), "scalar of type TEXT")
  expect_silent(.typeCheckVariable("x", c("a", "b"), "TEXT[]", TRUE))
  expect_error(.typeCheckVariable("x", c("a", NA_character_), "TEXT[]", TRUE), "contains NA")
  expect_error(.typeCheckVariable("x", character(0), "TEXT[]", TRUE), "non-empty vector")
})

test_that(".typeCheckVariable NUMERIC checks", {
  expect_silent(.typeCheckVariable("x", 3.14, "NUMERIC", FALSE))
  expect_silent(.typeCheckVariable("x", 1L, "NUMERIC", FALSE))
  expect_error(.typeCheckVariable("x", "a", "NUMERIC", FALSE), "scalar of type NUMERIC")
  expect_error(.typeCheckVariable("x", NA, "NUMERIC", FALSE), "contains NA")
  expect_error(.typeCheckVariable("x", NULL, "NUMERIC", FALSE), "not supplied")
  expect_error(.typeCheckVariable("x", c(1, 2), "NUMERIC", FALSE), "scalar of type NUMERIC")
  expect_silent(.typeCheckVariable("x", c(1.1, 2.2, 3.3), "NUMERIC[]", TRUE))
  expect_error(.typeCheckVariable("x", c(1.1, NA), "NUMERIC[]", TRUE), "contains NA")
  expect_error(.typeCheckVariable("x", numeric(0), "NUMERIC[]", TRUE), "non-empty vector")
})

test_that(".typeCheckVariable BOOLEAN checks", {
  expect_silent(.typeCheckVariable("x", TRUE, "BOOLEAN", FALSE))
  expect_silent(.typeCheckVariable("x", FALSE, "BOOLEAN", FALSE))
  expect_silent(.typeCheckVariable("x", 1, "BOOLEAN", FALSE))
  expect_silent(.typeCheckVariable("x", 0, "BOOLEAN", FALSE))
  expect_error(.typeCheckVariable("x", NA, "BOOLEAN", FALSE), "contains NA")
  expect_error(.typeCheckVariable("x", NULL, "BOOLEAN", FALSE), "not supplied")
  expect_error(.typeCheckVariable("x", c(TRUE, FALSE), "BOOLEAN", FALSE), "scalar of type BOOLEAN")
  expect_silent(.typeCheckVariable("x", c(TRUE, FALSE), "BOOLEAN[]", TRUE))
  expect_silent(.typeCheckVariable("x", c(TRUE, 1, 0), "BOOLEAN[]", TRUE))
  expect_error(.typeCheckVariable("x", c(TRUE, NA), "BOOLEAN[]", TRUE), "contains NA")
  expect_error(.typeCheckVariable("x", logical(0), "BOOLEAN[]", TRUE), "non-empty vector")
})

test_that(".typeCheckVariable unknown type", {
  expect_error(.typeCheckVariable("x", 1, "UNKNOWN", FALSE), "Unknown type check")
})